# Generated by Django 2.0.9 on 2018-11-12 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0004_auto_20181112_1817'),
        ('oneonone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_title', models.CharField(max_length=100)),
                ('os', models.CharField(choices=[('ios', 'iOS'), ('aos', 'AOS')], max_length=20)),
                ('app_title_eng', models.CharField(blank=True, max_length=100)),
                ('events', models.TextField(blank=True)),
                ('tracking_url', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impression_id', models.TextField()),
                ('modified_url', models.TextField()),
                ('adid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.DeviceAdId')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oneonone.App')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_msg', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oneonone.App')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='oneonone',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
