# Generated by Django 2.0.9 on 2018-11-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneonone', '0002_auto_20181112_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oneonone.Content'),
        ),
    ]
