# Generated by Django 2.0.9 on 2018-11-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneonone', '0004_auto_20181112_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content', to='oneonone.App'),
        ),
        migrations.AlterField(
            model_name='result',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result', to='oneonone.Content'),
        ),
    ]
