# Generated by Django 2.0.9 on 2018-11-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneonone', '0005_auto_20181118_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='oneonone.App'),
        ),
        migrations.AlterField(
            model_name='result',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='oneonone.Content'),
        ),
    ]
