# Generated by Django 2.0.9 on 2018-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('pso', 'PSO'), ('game', 'GAME'), ('ops', 'OPS'), ('brand', 'BRAND'), ('bd', 'BD'), ('not-specified', 'Not Specified')], max_length=80, null=True),
        ),
    ]
