# Generated by Django 2.0.9 on 2018-11-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20181112_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(choices=[('ios', 'iOS'), ('aos', 'AOS')], max_length=30),
        ),
    ]
