# Generated by Django 2.0.9 on 2018-11-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20181112_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceadid',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.Device'),
        ),
    ]
