# Generated by Django 2.0.9 on 2018-11-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20181112_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
