# Generated by Django 2.0.9 on 2018-11-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20181113_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceadid',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adids', to='devices.Device'),
        ),
    ]
