# Generated by Django 2.0.9 on 2018-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20181113_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
